const CAR_LIST = [
  {
    id: 0,
    name: "Kia, low budget baby boy",
    make: "kia",
    model: "seranto",
    fuelType: "petrol",
    bodyType: "sedan",
    releaseDate: "2016",
    mileage: "25000",
    price: "40000",
  },
  {
    id: 1,
    name: "Accordionizational vehicle",
    make: "honda",
    model: "accord",
    fuelType: "hybrid",
    bodyType: "suv",
    releaseDate: "2017",
    mileage: "50000",
    price: "30000",
  },
  {
    id: 2,
    name: "tekken",
    make: "honda",
    model: "accord",
    fuelType: "diesel",
    bodyType: "hatchback",
    releaseDate: "2005",
    mileage: "40000",
    price: "20000",
  },
  {
    id: 3,
    name: "last of us",
    make: "honda",
    model: "accord",
    fuelType: "petrol",
    bodyType: "suv",
    releaseDate: "2014",
    mileage: "90000",
    price: "60000",
  },
  {
    id: 4,
    name: "Toyota Corrolla Bolt",
    make: "toyota",
    model: "corolla",
    fuelType: "diesel",
    bodyType: "truck",
    releaseDate: "2013",
    mileage: "35000",
    price: "50000",
  },
  {
    id: 5,
    name: "call of duty",
    make: "honda",
    model: "accord",
    fuelType: "diesel",
    bodyType: "sedan",
    releaseDate: "2011",
    mileage: "78000",
    price: "50000",
  },
  {
    id: 6,
    name: "red dead redemption",
    make: "honda",
    model: "accord",
    fuelType: "diesel",
    bodyType: "suv",
    releaseDate: "2003",
    mileage: "28000",
    price: "50000",
  },
  {
    id: 7,
    name: "halo",
    make: "honda",
    model: "accord",
    fuelType: "petrol",
    bodyType: "sedan",
    releaseDate: "2019",
    mileage: "25000",
    price: "60000",
  },
  {
    id: 8,
    name: "Baby Boy",
    make: "toyota",
    model: "avalon",
    fuelType: "petrol",
    bodyType: "sedan",
    releaseDate: "2018",
    mileage: "50000",
    price: "70000",
  },
  {
    id: 9,
    name: "Evil Spirit",
    make: "honda",
    model: "accord",
    fuelType: "petrol",
    bodyType: "truck",
    releaseDate: "2003",
    mileage: "50000",
    price: "100000",
  },
  {
    id: 10,
    name: "Akira",
    make: "kia",
    model: "seranto",
    fuelType: "diesel",
    bodyType: "truck",
    releaseDate: "2016",
    mileage: "25000",
    price: "40000",
  },
];

export default CAR_LIST;
